local_costmap:
  global_frame: odom
  robot_base_frame: robot_footprint 
  update_frequency: 1.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 10.0
  height: 10.0
  resolution: 0.05
  
  plugins:
    - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_global,          type: "costmap_2d::InflationLayer"}
    - {name: inflation_local,           type: "costmap_2d::InflationLayer"}